spring:
  datasource:
    data: classpath:db/data.sql
    schema: classpath:db/schema.sql
<<<<<<< HEAD
    url: jdbc:h2:tcp://localhost/D:\h2WorkSpace\h2test;MODE=MySql;DB_CLOSE_DELAY=-1
=======
    url: jdbc:h2:D:\h2WorkSpace/h2test;MODE=MySql;DB_CLOSE_DELAY=-1
>>>>>>> b29f34711a9d9ab55a167b68ad0a4d0c7ef51339
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
server:
  port: 8888